drop extension if exists "pg_net";


  create table "public"."sentence_list" (
    "id" integer generated by default as identity not null,
    "sentence" text not null,
    "sentenceImage" text not null,
    "uid" uuid default auth.uid()
      );


alter table "public"."sentence_list" enable row level security;


  create table "public"."user" (
    "user_name" text,
    "uid" uuid not null
      );


alter table "public"."user" enable row level security;


  create table "public"."word_list" (
    "en_word" text not null,
    "ja_word" text not null,
    "id" bigint generated by default as identity not null,
    "image" text not null,
    "isSentence" boolean not null default false,
    "uid" uuid default auth.uid()
      );


alter table "public"."word_list" enable row level security;

CREATE UNIQUE INDEX sentence_list_pkey ON public.sentence_list USING btree (id);

CREATE UNIQUE INDEX user_pkey ON public."user" USING btree (uid);

CREATE UNIQUE INDEX word_list_pkey ON public.word_list USING btree (id);

alter table "public"."sentence_list" add constraint "sentence_list_pkey" PRIMARY KEY using index "sentence_list_pkey";

alter table "public"."user" add constraint "user_pkey" PRIMARY KEY using index "user_pkey";

alter table "public"."word_list" add constraint "word_list_pkey" PRIMARY KEY using index "word_list_pkey";

alter table "public"."sentence_list" add constraint "sentence_list_id_fkey" FOREIGN KEY (id) REFERENCES public.word_list(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."sentence_list" validate constraint "sentence_list_id_fkey";

alter table "public"."sentence_list" add constraint "sentence_list_uid_fkey" FOREIGN KEY (uid) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."sentence_list" validate constraint "sentence_list_uid_fkey";

alter table "public"."user" add constraint "user_uid_fkey" FOREIGN KEY (uid) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user" validate constraint "user_uid_fkey";

alter table "public"."word_list" add constraint "word_list_uid_fkey1" FOREIGN KEY (uid) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."word_list" validate constraint "word_list_uid_fkey1";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.user (uid, user_name)
  values (
    new.id,
    new.raw_user_meta_data ->> 'user_name'
  );

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

grant delete on table "public"."sentence_list" to "anon";

grant insert on table "public"."sentence_list" to "anon";

grant references on table "public"."sentence_list" to "anon";

grant select on table "public"."sentence_list" to "anon";

grant trigger on table "public"."sentence_list" to "anon";

grant truncate on table "public"."sentence_list" to "anon";

grant update on table "public"."sentence_list" to "anon";

grant delete on table "public"."sentence_list" to "authenticated";

grant insert on table "public"."sentence_list" to "authenticated";

grant references on table "public"."sentence_list" to "authenticated";

grant select on table "public"."sentence_list" to "authenticated";

grant trigger on table "public"."sentence_list" to "authenticated";

grant truncate on table "public"."sentence_list" to "authenticated";

grant update on table "public"."sentence_list" to "authenticated";

grant delete on table "public"."sentence_list" to "service_role";

grant insert on table "public"."sentence_list" to "service_role";

grant references on table "public"."sentence_list" to "service_role";

grant select on table "public"."sentence_list" to "service_role";

grant trigger on table "public"."sentence_list" to "service_role";

grant truncate on table "public"."sentence_list" to "service_role";

grant update on table "public"."sentence_list" to "service_role";

grant delete on table "public"."user" to "anon";

grant insert on table "public"."user" to "anon";

grant references on table "public"."user" to "anon";

grant select on table "public"."user" to "anon";

grant trigger on table "public"."user" to "anon";

grant truncate on table "public"."user" to "anon";

grant update on table "public"."user" to "anon";

grant delete on table "public"."user" to "authenticated";

grant insert on table "public"."user" to "authenticated";

grant references on table "public"."user" to "authenticated";

grant select on table "public"."user" to "authenticated";

grant trigger on table "public"."user" to "authenticated";

grant truncate on table "public"."user" to "authenticated";

grant update on table "public"."user" to "authenticated";

grant delete on table "public"."user" to "service_role";

grant insert on table "public"."user" to "service_role";

grant references on table "public"."user" to "service_role";

grant select on table "public"."user" to "service_role";

grant trigger on table "public"."user" to "service_role";

grant truncate on table "public"."user" to "service_role";

grant update on table "public"."user" to "service_role";

grant delete on table "public"."word_list" to "anon";

grant insert on table "public"."word_list" to "anon";

grant references on table "public"."word_list" to "anon";

grant select on table "public"."word_list" to "anon";

grant trigger on table "public"."word_list" to "anon";

grant truncate on table "public"."word_list" to "anon";

grant update on table "public"."word_list" to "anon";

grant delete on table "public"."word_list" to "authenticated";

grant insert on table "public"."word_list" to "authenticated";

grant references on table "public"."word_list" to "authenticated";

grant select on table "public"."word_list" to "authenticated";

grant trigger on table "public"."word_list" to "authenticated";

grant truncate on table "public"."word_list" to "authenticated";

grant update on table "public"."word_list" to "authenticated";

grant delete on table "public"."word_list" to "service_role";

grant insert on table "public"."word_list" to "service_role";

grant references on table "public"."word_list" to "service_role";

grant select on table "public"."word_list" to "service_role";

grant trigger on table "public"."word_list" to "service_role";

grant truncate on table "public"."word_list" to "service_role";

grant update on table "public"."word_list" to "service_role";


  create policy "User can select sentence."
  on "public"."sentence_list"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = uid));



  create policy "Users can create a sentence."
  on "public"."sentence_list"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = uid));



  create policy "Users can delete a sentence."
  on "public"."sentence_list"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) = uid));



  create policy "User can select there data"
  on "public"."user"
  as restrictive
  for select
  to authenticated
using (( SELECT (auth.uid() = "user".uid)));



  create policy "Users can create a word."
  on "public"."word_list"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = uid));



  create policy "Users can delete a word."
  on "public"."word_list"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) = uid));



  create policy "Users can update isSentence boolean."
  on "public"."word_list"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) = uid))
with check ((( SELECT auth.uid() AS uid) = uid));



  create policy "user can select there own word"
  on "public"."word_list"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = uid));


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "User can delete their images"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'images'::text) AND (owner_id = ( SELECT (auth.uid())::text AS uid))));



  create policy "User can insert their files"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'images'::text) AND ((storage.foldername(name))[1] = (( SELECT auth.uid() AS uid))::text)));



  create policy "User can view their files"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'images'::text) AND ((storage.foldername(name))[1] = (( SELECT auth.uid() AS uid))::text)));



